### ISSUE TITLE
[Add App] Recreate-Startmenu-Shortcuts.ps1 - Bomgar Representative Console

### ISSUE THREAD

**Issue by mruby88** [Andrew-J-Larson/OS-Scripts#21]
Hi AlienDrew,

here are the files you asked for for the Bomgar Representative Console

Thank you muchly!
- User Install: [Representative Console (help.culvers.com).zip](https://github.com/TheAlienDrew/OS-Scripts/files/10451640/Representative.Console.help.culvers.com.zip)
- System Install: [Representative Console (help.culvers.com).zip](https://github.com/TheAlienDrew/OS-Scripts/files/10451641/Representative.Console.help.culvers.com.zip)

_Edited by @TheAlienDrew for clarity `2023-01-19T01:27:06Z`_

**Comment by mruby88** [comment]
Hi AlienDrew,

There is not Bomgar path in the program files folder

Here is the output for AppData\Local\Bomgar\bomgar-rep\:
[A screenshot of a computer  Description automatically generated with medium confidence]

**Comment by TheAlienDrew** [comment]
> Hi AlienDrew, There is not Bomgar path in the program files folder Here is the output for AppData\Local\Bomgar\bomgar-rep\: [A screenshot of a computer Description automatically generated with medium confidence]
> […](#)
> _Edited by @TheAlienDrew to remove extra unneeded email bits_

That image didn't upload to GitHub through your email, please open the GitHub website to this issue and upload there.

**Comment by TheAlienDrew** [comment]
@mruby88 can you upload that image here, or just copy paste the output from terminal?

**Comment by TheAlienDrew** [comment]
> Hi AlienDrew,
> 
> here are the files you asked for for the Bomgar Representative Console
> 
> Thank you muchly!
> 
> * User Install: [Representative Console (help.culvers.com).zip](https://github.com/TheAlienDrew/OS-Scripts/files/10451640/Representative.Console.help.culvers.com.zip)
> * System Install: [Representative Console (help.culvers.com).zip](https://github.com/TheAlienDrew/OS-Scripts/files/10451641/Representative.Console.help.culvers.com.zip)
> 
> _Edited by @TheAlienDrew for clarity `2023-01-19T01:27:06Z`_

Also from where on the PC were the shortcuts located? (e.g. `C:\ProgramData\Microsoft\Windows\Start Menu\Programs\...`)

**Comment by TheAlienDrew** [comment]
@mruby88 could send over the paths to where those are both inside of the Programs folder (user and system locations)?
