### ISSUE TITLE
reupload Download-AppxPackage-Function.ps1

### ISSUE THREAD

**Issue by IveMalfunctioned** [Andrew-J-Larson/OS-Scripts#29]
I found it here:
https://stackoverflow.com/questions/73217411/permanent-direct-download-links-to-microsoft-store-appxbundle

I am looking to use its functions in my own script.

**Comment by Andrew-J-Larson** [comment]
It's located here now: https://github.com/Andrew-J-Larson/OS-Scripts/blob/main/Windows/Wrapper-Functions/Get-AppxPackage-Function.ps1
