### ISSUE TITLE
403 forbidden on API calls to  adguard store

### ISSUE THREAD

**Issue by agentoranger** [Andrew-J-Larson/OS-Scripts#30]
https://github.com/Andrew-J-Larson/OS-Scripts/tree/main/Windows/Wrapper-Functions

The wrapper functions and the related powershell modules that use it, that interact with adguard api all return 403, how did you get this working?

**Comment by Andrew-J-Larson** [comment]
What package were you trying to download?? Have you tried other packages?

**Comment by Andrew-J-Larson** [comment]
Just took a quick look myself, and I'm guessing the API is now requiring more information to be sent in with API requests, I'll see what I can do the next time I have free time to work on this.

**Comment by Andrew-J-Larson** [comment]
@agentoranger I'm unsure if it affected it, but I did realized the changed function name I gave it (`Get-AppxPackage`) was technically already used by PowerShell by default to list packages on the machine, so I renamed it back to what I originally had it as (`Download-AppxPackage`).

I tested it today, and it seems to be working fine. If you're still getting 403 errors when trying to download a package, let me know what region your ISP is from, and test to confirm you can even access the adgaurd.net website from your internet.

Additionally, let me know what package you're trying to download.

But for now, I'm going to go ahead and close this ticket.

**Comment by agentoranger** [comment]
![image](https://github.com/Andrew-J-Larson/OS-Scripts/assets/9388401/4a35939f-325c-4c79-a806-46b908189495)

I'm not certain the real cause, but I went ahead tried the updated code and I am seeing a similar error, like what it seen above. 
 Perhaps the API is restricted based on geo location, I am in the United states.  

I worked around it using the code found on this project
https://dev.to/antidisestablishmentarianism/powershell-script-to-download-appx-files-from-the-microsoft-store-for-currently-installed-packages-501e

I do plan to dig into the windows update method to see if I can select a specific package by name as your original script intends to do.  In this case, I have review similar scripts that attempt to use adguard and I experience a similar problem resulting in 403.  

I don't think the issue is exclusive to your code. 

I would totally understand if you do not have time to look into this further, it was nice of you try to resolve the issue, and I appreciate your time.

**Comment by agentoranger** [comment]
I just attempted the same connection from vpn in Germany and the issue persists, perhaps that was not a great guess on my part.

**Comment by Andrew-J-Larson** [comment]
> I just attempted the same connection from vpn in Germany and the issue persists, perhaps that was not a great guess on my part.

My ISP is based in the US, so it couldn't be quite that.

However, although adguard uses a `.net` domain suffix, it's API is hosted on Russian servers. So, if you are using a company device, or some sort of personal antivirus, that blocks connections to Russian websites, that's the more likely reason why you're getting a 403 error.

**Comment by agentoranger** [comment]
I ran another test in powershell core, which I dont use very often and seen a new result, I will investigate this more in time:

![image](https://github.com/Andrew-J-Larson/OS-Scripts/assets/9388401/958330f9-fc32-4400-a283-68f563e1ae86)

**Comment by Andrew-J-Larson** [comment]
> I ran another test in powershell core, which I dont use very often and seen a new result, I will investigate this more in time:
> 
> ![image](https://private-user-images.githubusercontent.com/9388401/311573779-958330f9-fc32-4400-a283-68f563e1ae86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxMjYxOTcsIm5iZiI6MTcxMDEyNTg5NywicGF0aCI6Ii85Mzg4NDAxLzMxMTU3Mzc3OS05NTgzMzBmOS1mYzMyLTQ0MDAtYTI4My02OGY1NjNlMWFlODYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTFUMDI1ODE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmEwOWM5MmVhYWU3MmFmOTE0ZWFiZDc0OTIzM2JjNWNkNmFmYmI5NGI0MjM4YTc3N2RjNTA5YjBhM2E1YjRhMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.g9taHaNG9eHB36PNKQLpYQeVacLVKp3e7a_IDuhhmww)

Yes, this is normally what I get, if I try running the script at my place of work (which does block Russian websites).

That's why I assume it's something on your end also blocking the API.

**Comment by agentoranger** [comment]
Okay, mystery solved, in my case, I need both Powershell Core and to Jump on VPN, I am blocking some things on my home network, but nothing specific to russia, its possible some of the pfBlockerNG rule sets are blocking commination when it sent over API.  Honestly, I would have never guessed, the site works normally from a browser, but I have enough information that I can work around it and possibly fix it later for good.  When I am finished with my current project, I will circle back and see if I can write a check for that and share it with you.  

![image](https://github.com/Andrew-J-Larson/OS-Scripts/assets/9388401/225218b9-72fe-4e77-8416-96feee8804d1)

**Comment by agentoranger** [comment]
Do you have ipv6 working at your location?

![image](https://github.com/Andrew-J-Larson/OS-Scripts/assets/9388401/24ce30d7-824c-4720-a768-6a67fb6c6a04)

**Comment by Andrew-J-Larson** [comment]
> Do you have ipv6 working at your location?
> 
> ![image](https://private-user-images.githubusercontent.com/9388401/311575802-24ce30d7-824c-4720-a768-6a67fb6c6a04.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxMjcwNDAsIm5iZiI6MTcxMDEyNjc0MCwicGF0aCI6Ii85Mzg4NDAxLzMxMTU3NTgwMi0yNGNlMzBkNy04MjRjLTQ3MjAtYTc2OC02YTY3ZmI2YzZhMDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTFUMDMxMjIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDhlY2VlM2QyMmRmNjY5YjQ4MWNkNzJjOGEwOTM3MjQ1YzU2MWJmYWJlNGE0OTM5NjUyYzNjOTJmMjEzYzZiNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.rrkjae7UYKGt9HdGpOB7gX2K6-ZP2kTJfqYiP9TYo34)

That's actually a good point, I think mine mainly goes through ipv4, so I suppose I might just need to force the script to make the API requests stay on ipv4 somehow.

**Comment by agentoranger** [comment]
I will try that, standby

**Comment by Andrew-J-Larson** [comment]
> I will try that, standby

See what `[Net.ServicePointManager]::SecurityProtocol` displays when running it from Windows PowerShell (v5.1), and then again from Core.

**Comment by agentoranger** [comment]
Is it not related to ipv6, I was able to confirm that.

Windows Powershell
![image](https://github.com/Andrew-J-Larson/OS-Scripts/assets/9388401/c53fe081-9d30-4807-9b38-a05ba5edf40f)

Powershell Core
![image](https://github.com/Andrew-J-Larson/OS-Scripts/assets/9388401/13282f6a-3b53-40bc-9021-142644738a90)

**Comment by agentoranger** [comment]
Tls12 and Tls13 does not change the outcome, this is starting to look like a blocked IP or URL when over VPN the issue does not occur on default, Tls12 or Tls13

**Comment by Andrew-J-Larson** [comment]
> Tls12 and Tls13 does not change the outcome, this is continuing to look like a blocked IP or URL when over VPN the issue does not occur on default, Tls12 or Tls13

I was able to figure something else out, it looks like the API is hosted through CloudFlare. I'm guessing it's not liking your IP, assuming you probably do a lot of webscraping already.

Edit the script at the `Invoke-RestMethod` line, and include the following at the end of it: `-UserAgent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"`

Let me know if that changes the results when ran in either PowerShell version

**Comment by agentoranger** [comment]
Yes, that fixes it!!  Line 98 I do beleive
-UserAgent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"

**Comment by agentoranger** [comment]
This issue is close, Andrew is the man. certifiably.

**Comment by Andrew-J-Larson** [comment]
> This issue is closed, Andrew is the man. certifiably.

I updated the script on my end, test the new script to see if that works (trying to use the built in Chrome UA that powershell has). If that works then great, if not, then I'll need to code in a little extra bits to grab the latest UA from somewhere online.

**Comment by agentoranger** [comment]
This is now working in both Powershell 5 and Powershell Core. Nicely done Andrew
